### ISSUE TITLE
Can great circle distance be supported?

### ISSUE THREAD

**Issue by JCatwood** [ecrc/exageostatR#3]
For the estimation function, it will be nicer if latitude and longitude can be supported as the inputs for `x` and `y`. Thus there will be another parameter indicating whether great circle distance should be applied.

**Comment by SAbdulah** [comment]
a new function is support in v 1.0.0 ,  i.e., `exageostat_egenz_glR()`. Moreover, for the generation, estimation, and prediction functions, the distance metric can be given as a function parameter (0-->ED, 1-->GCD) to select the way the Matern kernel should calculate the covariance matrix.
